---
name: Python package

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14.0-beta - 3.14"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Lint with mypy
        run: |
          mypy .

      - name: Check rules with ruff
        run: |
          ruff check .

      - name: Format with ruff
        run: |
          ruff format .
  test_deploy:
    runs-on: ubuntu-latest
    name: Publish on Test PyPi
    if: github.event_name == 'push'
    needs:
      - build

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev] build

      - name: Build Python package
        run: |
          python -m build .

      - name: Publish package to Test PyPi
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # v1.12.4
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
